### ISSUE TITLE
Python v2.6.4 script

### ISSUE THREAD

**Issue by sdbhatia** [Onapsis/onapsis_icmad_scanner#2]
Hi,

Thank you for this script, however, in a Solaris environment that's running Python 2.6.4, this script is showing a syntax error.

What changes are to be done to ensure it runs on Python 2.6.4 too? It is not my expertise, I'd appreciate any support. Thanks.

**Comment by nahueldsanchez** [comment]
Hello, please remember this tool is provided with no support.

The tool was developed to be run using Python3. If your system does not have it installed it is recommended to run it from another host where you have at least Python v3.7 installed if you are not capable of performing the changes to run it using Python 2.x.
